Repository ormi3-final-project-team/nolreo_wassup_FE, pull requests merged in 2023-12, with the labels that each got.

#4 :sparkles: Feat: 로그인, 회원가입 페이지 구현
  login.html
  signup.html
Labels: enhancement

#5 :sparkles: Feat: 프로필 페이지 구현
  editprofile.html
  profile.html
Labels: enhancement

#14 :sparkles: Feat: 예약 목록 페이지 구현
  reservation-list.html
Labels: enhancement

#20 :sparkles: Feat: variable add
  js/custom/common.js
  js/custom/signup.js
  signup.html
Labels: enhancement

#21 :bug: Fix: 검색 목록 UI 수정
  css/custom/index.css
  index.html
  js/custom/index.js
  lodging_booking.html
  rentalcar_booking.html
  style.css
Labels: enhancement

#22 :sparkles: Feat: Client -> API 회원가입, 로그인 요청 개발
  js/custom/common.js
  js/custom/login.js
  js/custom/signup.js
  login.html
  signup.html
Labels: enhancement

#24 :bug: Fix: 회원가입 시 프로필 사진 추가할 수 있도록 수정 & 로그인 시 응답 값 로컬 스토리지에 저장하도록 수정
  js/custom/common.js
  js/custom/login.js
  js/custom/signup.js
  signup.html
Labels: enhancement

#26 :sparkles: Feat: 네비게이션 바 로그인, 미로그인 시 구분 출력
  index.html
  js/custom/common.js
Labels: enhancement

#27 :bug: Fix: 네이게이션바 클래스명 중복 수정
  index.html
  js/custom/common.js
Labels: bug

#28 :sparkles: Feat: Client -> API 프로필 회원 탈퇴, 수정 요청 개발
  editprofile.html
  js/custom/common.js
  js/custom/editprofile.js
  js/custom/profile.js
  profile.html
Labels: enhancement

#32 :sparkles: Feat: 메인 페이지 수정 및 API 연동(리스트, 찜)
  index.html
  js/custom/common.js
  js/custom/lodging_details.js
  js/custom/main_lodging_list.js
Labels: enhancement

#37 :sparkles: Feat: 조건 검색 기능 추가
  index.html
  js/custom/main_lodging_list.js
Labels: enhancement

#38 ✨ Feat: 숙소 상세 페이지
  css/custom/lodging_details.css
  js/custom/lodging_details.js
  js/custom/lodging_reservation.js
  lodging-details.html
  lodging_reservation.html
  rentalcar_reservation.html
  traffic_reservation.html
Labels: enhancement

#40 :sparkles: Feat: 예약 페이지 수정 및 버스, 기차 예약 API 연동 개발
  js/custom/main_lodging_list.js
  js/custom/main_rentcar_list.js
  js/custom/main_transport_list.js
  js/custom/traffic_reservation.js
  lodging_reservation.html
  rentalcar_reservation.html
  traffic_reservation.html
Labels: enhancement

#41 :bug: Fix: 교통(기차,버스) 찜 버튼 에러 수정
  js/custom/main_transport_list.js
Labels: bug, enhancement

#42 :bug: Fix: 검색 데이터타입 수정 & 예약 완료 후 메인 페이지 이동
  js/custom/traffic_reservation.js
  transport.html
Labels: bug, enhancement

#44 :sparkles: Feat: 숙소 상세 페이지 API 연동
  js/custom/lodging_details.js
  js/custom/login.js
  lodging-details.html
Labels: enhancement

#45 :bug: Fix: 전반적인 js 오류 수정
  images/lodging.jpg
  js/custom/lodging_details.js
  js/custom/lodging_reservation.js
  js/custom/main_lodging_list.js
  js/custom/main_rentcar_list.js
  js/custom/traffic_reservation.js
Labels: bug

#46 :sparkles: Feat: 숙소 상세 페이지 찜 API 연동
  js/custom/lodging_details.js
  js/custom/rentalcar_details.js
  lodging-details.html
  rentalcar-details.html
Labels: enhancement

#47 :bug: Fix: JavaScript 오류 해결
  README.md
  js/custom/main_lodging_list.js
  js/custom/reservation_list.js
Labels: bug

#48 :lipstick: Design: 메인페이지 숙소, 렌터카 이미지 크기 고정
  js/custom/main_lodging_list.js
  js/custom/main_rentcar_list.js
Labels: enhancement

#49 :sparkles: Feat: 렌트카 상세 페이지 API 연동
  css/custom/rentalcar_details.css
  js/custom/lodging_details.js
  js/custom/rentalcar_details.js
  rentalcar-details.html
Labels: enhancement

#50 :bug: Fix: JavaScript 코드 에러 수정
  js/custom/rentalcar_details.js
Labels: bug

#53 :bug: Fix: 개발 완료 후 코드 정리
  index.html
  js/custom/changepassword.js
  js/custom/editprofile.js
  js/custom/index.js
  js/custom/lodging_details.js
  js/custom/lodging_reservation.js
  js/custom/login.js
  js/custom/main_lodging_list.js
  js/custom/pick_list.js
  js/custom/profile.js
  js/custom/rentalcar_details.js
  js/custom/signup.js
  js/custom/traffic_reservation.js
Labels: bug

#54 🐛 Fix: 개발 완료 후 코드 정리
  index.html
  js/custom/changepassword.js
  js/custom/editprofile.js
  js/custom/index.js
  js/custom/lodging_details.js
  js/custom/lodging_reservation.js
  js/custom/login.js
  js/custom/main_lodging_list.js
  js/custom/pick_list.js
  js/custom/profile.js
  js/custom/rentalcar_details.js
  js/custom/signup.js
  js/custom/traffic_reservation.js
Labels: bug

#55 🐛 Fix: 개발 완료 후 코드 정리
  index.html
  js/custom/changepassword.js
  js/custom/editprofile.js
  js/custom/index.js
  js/custom/lodging_details.js
  js/custom/lodging_reservation.js
  js/custom/login.js
  js/custom/main_lodging_list.js
  js/custom/pick_list.js
  js/custom/profile.js
  js/custom/rentalcar_details.js
  js/custom/signup.js
  js/custom/traffic_reservation.js
Labels: bug
